// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA13T_g_m8hFRbu2dfzjKYv4bpODBgXuC0',
    appId: '1:678335579973:web:d3622e305815565adca02c',
    messagingSenderId: '678335579973',
    projectId: 'bedtime-stories-app-ccb9d',
    authDomain: 'bedtime-stories-app-ccb9d.firebaseapp.com',
    databaseURL: 'https://bedtime-stories-app-ccb9d-default-rtdb.firebaseio.com',
    storageBucket: 'bedtime-stories-app-ccb9d.appspot.com',
    measurementId: 'G-8JQVG4LXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQbRUHmVsRowdoPnwdN5_gyhgfTTy0r0',
    appId: '1:678335579973:android:1adedd6fe696fda6dca02c',
    messagingSenderId: '678335579973',
    projectId: 'bedtime-stories-app-ccb9d',
    databaseURL: 'https://bedtime-stories-app-ccb9d-default-rtdb.firebaseio.com',
    storageBucket: 'bedtime-stories-app-ccb9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNMUdUdUMH_PtoMmTfZhl7WHSTSme6SOU',
    appId: '1:678335579973:ios:90bb57d763406d86dca02c',
    messagingSenderId: '678335579973',
    projectId: 'bedtime-stories-app-ccb9d',
    databaseURL: 'https://bedtime-stories-app-ccb9d-default-rtdb.firebaseio.com',
    storageBucket: 'bedtime-stories-app-ccb9d.appspot.com',
    androidClientId: '678335579973-en73ugttfvc91u2okourqsbgtk11ahcr.apps.googleusercontent.com',
    iosClientId: '678335579973-tmufprq9esa36m6nvb7h20n0c7v5031c.apps.googleusercontent.com',
    iosBundleId: 'com.rafterco.barbs.bedtime.stories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNMUdUdUMH_PtoMmTfZhl7WHSTSme6SOU',
    appId: '1:678335579973:ios:90bb57d763406d86dca02c',
    messagingSenderId: '678335579973',
    projectId: 'bedtime-stories-app-ccb9d',
    databaseURL: 'https://bedtime-stories-app-ccb9d-default-rtdb.firebaseio.com',
    storageBucket: 'bedtime-stories-app-ccb9d.appspot.com',
    androidClientId: '678335579973-en73ugttfvc91u2okourqsbgtk11ahcr.apps.googleusercontent.com',
    iosClientId: '678335579973-tmufprq9esa36m6nvb7h20n0c7v5031c.apps.googleusercontent.com',
    iosBundleId: 'com.rafterco.barbs.bedtime.stories',
  );
}
